# Generated by Django 3.0.5 on 2020-05-01 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_product_review',
            field=models.ManyToManyField(through='product.Review', to='product.Product'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_review',
            field=models.ManyToManyField(through='product.ReviewLike', to='product.Review'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Country'),
        ),
    ]
