# Generated by Django 3.0.5 on 2020-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200427_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_detail',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
