# Generated by Django 3.0.5 on 2020-04-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_address_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address_detail',
        ),
    ]
