# Generated by Django 3.0.5 on 2020-04-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'privacies',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('business_hours', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'store_countries',
            },
        ),
        migrations.CreateModel(
            name='StoreDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('storecountry_storedistrict', models.ManyToManyField(through='information.Store', to='information.StoreCountry')),
            ],
            options={
                'db_table': 'store_districts',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='store_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.StoreCountry'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.StoreDistrict'),
        ),
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.QuestionType')),
            ],
            options={
                'db_table': 'frequent_questions',
            },
        ),
    ]
