# Generated by Django 3.0.5 on 2020-05-01 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order_status', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'baskets',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'delivery_status',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=45)),
                ('payment_method', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('detail_address', models.CharField(max_length=100)),
                ('shopping_charge', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.IntegerField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account')),
                ('delivery_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.DeliveryStatus')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
