# Generated by Django 3.0.5 on 2020-04-27 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20200427_0515'),
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_order',
            field=models.ManyToManyField(through='product.ProductOrder', to='product.Product'),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='account_deliverystatus',
            field=models.ManyToManyField(through='order.Order', to='account.Account'),
        ),
        migrations.AddField(
            model_name='basket',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account'),
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
